// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bumbo.Data;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(BumboDBContext))]
    partial class BumboDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<TimeOnly>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeOnly>("OpeningTime")
                        .HasColumnType("time");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrognosisId")
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("ShelfMeeters")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BranchId");

                    b.HasIndex("CountryName");

                    b.HasIndex("PrognosisId");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            BranchId = 1,
                            ClosingTime = new TimeOnly(18, 0, 0),
                            CountryName = "Netherlands",
                            HouseNumber = "10",
                            Name = "Amsterdam Filiaal",
                            OpeningTime = new TimeOnly(9, 0, 0),
                            PostalCode = "1012 LG",
                            ShelfMeeters = 0,
                            Street = "Damrak"
                        },
                        new
                        {
                            BranchId = 2,
                            ClosingTime = new TimeOnly(17, 0, 0),
                            CountryName = "Belgium",
                            HouseNumber = "20",
                            Name = "Brussels Filiaal",
                            OpeningTime = new TimeOnly(8, 0, 0),
                            PostalCode = "1000",
                            ShelfMeeters = 0,
                            Street = "Grote Markt"
                        },
                        new
                        {
                            BranchId = 3,
                            ClosingTime = new TimeOnly(21, 0, 0),
                            CountryName = "Netherlands",
                            HouseNumber = "2",
                            Name = "Alkmaar Filiaal",
                            OpeningTime = new TimeOnly(9, 0, 0),
                            PostalCode = "1811 KH",
                            ShelfMeeters = 0,
                            Street = "Paardenmarkt"
                        },
                        new
                        {
                            BranchId = 4,
                            ClosingTime = new TimeOnly(17, 0, 0),
                            CountryName = "Netherlands",
                            HouseNumber = "15",
                            Name = "Rotterdam Filiaal",
                            OpeningTime = new TimeOnly(9, 0, 0),
                            PostalCode = "3011 HE",
                            ShelfMeeters = 0,
                            Street = "Botersloot"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Availability", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Date", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Availability");
                });

            modelBuilder.Entity("DataLayer.Models.Department", b =>
                {
                    b.Property<string>("DepartmentName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DepartmentName");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentName = "Kassa"
                        },
                        new
                        {
                            DepartmentName = "Vakkenvullen"
                        },
                        new
                        {
                            DepartmentName = "Vers"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.EmployeeHasDepartment", b =>
                {
                    b.Property<string>("DepartmentName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DepartmentName", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeHasDepartment");
                });

            modelBuilder.Entity("DataLayer.Models.Function", b =>
                {
                    b.Property<string>("FunctionName")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("FunctionName");

                    b.ToTable("Functions");

                    b.HasData(
                        new
                        {
                            FunctionName = "Cashier"
                        },
                        new
                        {
                            FunctionName = "Stocker"
                        },
                        new
                        {
                            FunctionName = "Manager"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.LabourRules", b =>
                {
                    b.Property<string>("CountryName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AgeGroup")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<TimeOnly>("MaxEndTime")
                        .HasColumnType("time");

                    b.Property<int>("MaxHoursPerDay")
                        .HasColumnType("int");

                    b.Property<int>("MaxHoursPerWeek")
                        .HasColumnType("int");

                    b.Property<int>("MaxHoursWithSchool")
                        .HasColumnType("int");

                    b.Property<int>("MaxOvertimeHoursPerWeek")
                        .HasColumnType("int");

                    b.Property<int>("MaxShiftDuration")
                        .HasColumnType("int");

                    b.Property<int>("MaxWorkDaysPerWeek")
                        .HasColumnType("int");

                    b.Property<int>("MinRestDaysPerWeek")
                        .HasColumnType("int");

                    b.Property<int>("MinRestHoursBetweenShifts")
                        .HasColumnType("int");

                    b.Property<int>("MinutesOfBreak")
                        .HasColumnType("int");

                    b.Property<int>("NumHoursWorkedBeforeBreak")
                        .HasColumnType("int");

                    b.Property<decimal>("OvertimePayPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SickPayPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CountryName");

                    b.ToTable("LabourRules");
                });

            modelBuilder.Entity("DataLayer.Models.PrognosisHasDaysHasDepartment", b =>
                {
                    b.Property<string>("DepartmentName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DayName")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PrognosisId")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("AmountOfWorkersNeeded")
                        .HasColumnType("int");

                    b.Property<int>("HoursOfWorkNeeded")
                        .HasColumnType("int");

                    b.HasKey("DepartmentName", "DayName", "PrognosisId");

                    b.HasIndex("DayName", "PrognosisId");

                    b.ToTable("PrognosisHasDaysHasDepartment");

                    b.HasData(
                        new
                        {
                            DepartmentName = "Kassa",
                            DayName = "Monday",
                            PrognosisId = "prognosis_week_47_2024",
                            AmountOfWorkersNeeded = 3,
                            HoursOfWorkNeeded = 24
                        },
                        new
                        {
                            DepartmentName = "Vakkenvullen",
                            DayName = "Monday",
                            PrognosisId = "prognosis_week_47_2024",
                            AmountOfWorkersNeeded = 4,
                            HoursOfWorkNeeded = 32
                        },
                        new
                        {
                            DepartmentName = "Vers",
                            DayName = "Monday",
                            PrognosisId = "prognosis_week_47_2024",
                            AmountOfWorkersNeeded = 2,
                            HoursOfWorkNeeded = 16
                        },
                        new
                        {
                            DepartmentName = "Kassa",
                            DayName = "Tuesday",
                            PrognosisId = "prognosis_week_47_2024",
                            AmountOfWorkersNeeded = 2,
                            HoursOfWorkNeeded = 16
                        },
                        new
                        {
                            DepartmentName = "Vakkenvullen",
                            DayName = "Tuesday",
                            PrognosisId = "prognosis_week_47_2024",
                            AmountOfWorkersNeeded = 3,
                            HoursOfWorkNeeded = 24
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Schedule", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSick")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "BranchId", "Date");

                    b.HasIndex("BranchId");

                    b.HasIndex("DepartmentName");

                    b.HasIndex("TemplateId");

                    b.ToTable("Schedule");

                    b.HasData(
                        new
                        {
                            EmployeeId = "a1b1c1d1-1111-2222-3333-4444abcdabcd",
                            BranchId = 1,
                            Date = new DateOnly(2024, 11, 18),
                            DepartmentName = "Kassa",
                            EndTime = new TimeOnly(13, 0, 0),
                            IsFinal = true,
                            IsSick = false,
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            EmployeeId = "c4d4e5f6-78g9-0a12-d3e4-f5g6h7i8j9k0",
                            BranchId = 1,
                            Date = new DateOnly(2024, 11, 18),
                            DepartmentName = "Kassa",
                            EndTime = new TimeOnly(17, 0, 0),
                            IsFinal = true,
                            IsSick = false,
                            StartTime = new TimeOnly(13, 0, 0)
                        },
                        new
                        {
                            EmployeeId = "f7g7h8i9-01j2-3c45-g6h7-i8j9k0l1m2n3",
                            BranchId = 1,
                            Date = new DateOnly(2024, 11, 18),
                            DepartmentName = "Vakkenvullen",
                            EndTime = new TimeOnly(12, 0, 0),
                            IsFinal = true,
                            IsSick = true,
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            EmployeeId = "b2c2d2e2-2222-3333-4444-5555abcdefab",
                            BranchId = 1,
                            Date = new DateOnly(2024, 11, 18),
                            DepartmentName = "Vakkenvullen",
                            EndTime = new TimeOnly(16, 0, 0),
                            IsFinal = true,
                            IsSick = false,
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            EmployeeId = "b3c3d4e5-67f8-9a01-c2d3-e4f5g6h7i8j9",
                            BranchId = 1,
                            Date = new DateOnly(2024, 11, 18),
                            DepartmentName = "Vakkenvullen",
                            EndTime = new TimeOnly(21, 30, 0),
                            IsFinal = true,
                            IsSick = false,
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            EmployeeId = "e6f6g7h8-90i1-2b34-f5g6-h7i8j9k0l1m2",
                            BranchId = 1,
                            Date = new DateOnly(2024, 11, 18),
                            DepartmentName = "Vers",
                            EndTime = new TimeOnly(14, 0, 0),
                            IsFinal = true,
                            IsSick = false,
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            EmployeeId = "d5e5f6g7-89h0-1a23-e4f5-g6h7i8j9k0l1",
                            BranchId = 1,
                            Date = new DateOnly(2024, 11, 18),
                            DepartmentName = "Vers",
                            EndTime = new TimeOnly(18, 0, 0),
                            IsFinal = true,
                            IsSick = false,
                            StartTime = new TimeOnly(14, 0, 0)
                        },
                        new
                        {
                            EmployeeId = "f7g7h8i9-01j2-3c45-g6h7-i8j9k0l1m2n3",
                            BranchId = 1,
                            Date = new DateOnly(2024, 11, 19),
                            DepartmentName = "Vakkenvullen",
                            EndTime = new TimeOnly(18, 0, 0),
                            IsFinal = true,
                            IsSick = false,
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            EmployeeId = "e6f6g7h8-90i1-2b34-f5g6-h7i8j9k0l1m2",
                            BranchId = 1,
                            Date = new DateOnly(2024, 11, 19),
                            DepartmentName = "Vers",
                            EndTime = new TimeOnly(12, 0, 0),
                            IsFinal = true,
                            IsSick = false,
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            EmployeeId = "a1b1c1d1-1111-2222-3333-4444abcdabcd",
                            BranchId = 1,
                            Date = new DateOnly(2024, 11, 20),
                            DepartmentName = "Kassa",
                            EndTime = new TimeOnly(15, 0, 0),
                            IsFinal = false,
                            IsSick = false,
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            EmployeeId = "e6f6g7h8-90i1-2b34-f5g6-h7i8j9k0l1m2",
                            BranchId = 1,
                            Date = new DateOnly(2024, 11, 21),
                            DepartmentName = "Vers",
                            EndTime = new TimeOnly(17, 0, 0),
                            IsFinal = true,
                            IsSick = false,
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            EmployeeId = "c4d4e5f6-78g9-0a12-d3e4-f5g6h7i8j9k0",
                            BranchId = 1,
                            Date = new DateOnly(2024, 11, 22),
                            DepartmentName = "Kassa",
                            EndTime = new TimeOnly(20, 0, 0),
                            IsFinal = true,
                            IsSick = true,
                            StartTime = new TimeOnly(12, 0, 0)
                        },
                        new
                        {
                            EmployeeId = "f7g7h8i9-01j2-3c45-g6h7-i8j9k0l1m2n3",
                            BranchId = 1,
                            Date = new DateOnly(2024, 11, 23),
                            DepartmentName = "Vakkenvullen",
                            EndTime = new TimeOnly(17, 0, 0),
                            IsFinal = true,
                            IsSick = false,
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            EmployeeId = "b3c3d4e5-67f8-9a01-c2d3-e4f5g6h7i8j9",
                            BranchId = 1,
                            Date = new DateOnly(2024, 11, 24),
                            DepartmentName = "Kassa",
                            EndTime = new TimeOnly(16, 0, 0),
                            IsFinal = true,
                            IsSick = false,
                            StartTime = new TimeOnly(8, 0, 0)
                        });
                });

            modelBuilder.Entity("DataLayer.Models.SchoolSchedule", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Date", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("SchoolSchedule");
                });

            modelBuilder.Entity("DataLayer.Models.SwitchRequest", b =>
                {
                    b.Property<string>("SendToEmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("Declined")
                        .HasColumnType("bit");

                    b.HasKey("SendToEmployeeId", "EmployeeId", "BranchId", "Date");

                    b.HasIndex("EmployeeId", "BranchId", "Date");

                    b.ToTable("SwitchRequest");
                });

            modelBuilder.Entity("Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("BID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("HouseNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsSystemManager")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ManagerOfBranchId")
                        .HasColumnType("int");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerOfBranchId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "f7g7h8i9-01j2-3c45-g6h7-i8j9k0l1m2n3",
                            AccessFailedCount = 0,
                            BID = "B001",
                            BirthDate = new DateTime(1985, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
<<<<<<< HEAD
                            ConcurrencyStamp = "eb785ef7-18d4-4157-af95-ca5e45b8a66d",
=======
                            ConcurrencyStamp = "8cd02a9b-0f93-4204-a738-4c3d39d99da2",
>>>>>>> development
                            Email = "john.doe@example.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            HouseNumber = 10,
                            IsSystemManager = true,
                            LastName = "Doe",
                            LockoutEnabled = false,
                            ManagerOfBranchId = 1,
                            MiddleName = "A.",
                            NormalizedEmail = "JOHN.DOE@EXAMPLE.COM",
                            NormalizedUserName = "JOHN.DOE@EXAMPLE.COM",
<<<<<<< HEAD
                            PasswordHash = "AQAAAAIAAYagAAAAEGdg7ZDnTtRBQA11BP9uYuEv7wQjfmnymGYaf1kVFj3eJ65CD/1T8pexye3VWMUZzQ==",
                            PhoneNumber = "06-9876543",
                            PhoneNumberConfirmed = false,
                            PostalCode = "12345",
                            SecurityStamp = "7ba5c925-db19-49a9-b7ae-510f7464707a",
=======
                            PasswordHash = "AQAAAAIAAYagAAAAEAXzXdA5pvnofT4rCzEoPe4CCMrUFR/FcmJ6NCTRjqlkw/OR/t9XycWbY36zNy4Srw==",
                            PhoneNumber = "06-9876543",
                            PhoneNumberConfirmed = false,
                            PostalCode = "12345",
                            SecurityStamp = "615e744c-861c-4db6-acbb-44f23ea60f7f",
>>>>>>> development
                            StartDate = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UserName = "john.doe@example.com"
                        },
                        new
                        {
                            Id = "e6f6g7h8-90i1-2b34-f5g6-h7i8j9k0l1m2",
                            AccessFailedCount = 0,
                            BID = "B002",
                            BirthDate = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
<<<<<<< HEAD
                            ConcurrencyStamp = "46c8121e-2784-4d56-b47a-caac2a69e4c8",
=======
                            ConcurrencyStamp = "3eed4ef2-cb53-4dce-8691-75fdce73f955",
>>>>>>> development
                            Email = "jane.smith@example.com",
                            EmailConfirmed = true,
                            FirstName = "Jane",
                            HouseNumber = 22,
                            IsSystemManager = false,
                            LastName = "Smith",
                            LockoutEnabled = false,
                            MiddleName = "B.",
                            NormalizedEmail = "JANE.SMITH@EXAMPLE.COM",
                            NormalizedUserName = "JANE.SMITH@EXAMPLE.COM",
<<<<<<< HEAD
                            PasswordHash = "AQAAAAIAAYagAAAAEM+f+vIB6sSBX5FPl/wKvYNUu3JL2x5icHupVriepKv6Ys2nbU1TuYjM17vk6d7pwQ==",
                            PhoneNumber = "06-12345678",
                            PhoneNumberConfirmed = false,
                            PostalCode = "9271 GB",
                            SecurityStamp = "89f735f5-da0e-4bac-a8e7-61a3eeb3a42d",
=======
                            PasswordHash = "AQAAAAIAAYagAAAAEFW7J/FXrB3Paw0OyYU1ng3Y2yF7R+Rkm0xbqYGl4HS/ppaRCbVk8Puqpt5Ep0Grmw==",
                            PhoneNumber = "06-12345678",
                            PhoneNumberConfirmed = false,
                            PostalCode = "9271 GB",
                            SecurityStamp = "0a5279ce-9ad2-46f8-953b-167238c3df23",
>>>>>>> development
                            StartDate = new DateTime(2012, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UserName = "jane.smith@example.com"
                        },
                        new
                        {
                            Id = "a2b2d3e4-56f7-8a90-b1c2-d3e4f5g6h7i8",
                            AccessFailedCount = 0,
                            BID = "B003",
                            BirthDate = new DateTime(1992, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
<<<<<<< HEAD
                            ConcurrencyStamp = "fe26c545-025f-4731-ad46-f2887193dc8f",
=======
                            ConcurrencyStamp = "0f2459eb-805d-48f0-9072-684d32825d03",
>>>>>>> development
                            Email = "darlon.vandijk@hotmail.com",
                            EmailConfirmed = true,
                            FirstName = "Darlon",
                            HouseNumber = 5,
                            IsSystemManager = false,
                            LastName = "van Dijk",
                            LockoutEnabled = false,
                            MiddleName = "",
                            NormalizedEmail = "DARLON.VANDIJK@HOTMAIL.COM",
                            NormalizedUserName = "DARLON.VANDIJK@HOTMAIL.COM",
<<<<<<< HEAD
                            PasswordHash = "AQAAAAIAAYagAAAAEHt+44JUrb03qI4HlCUDGJUpcUEstVNC6LpJRd442Dl7h7sieNRuo0eOAJfWJV1K7g==",
                            PhoneNumber = "+31 6 34567890",
                            PhoneNumberConfirmed = false,
                            PostalCode = "8329 SK",
                            SecurityStamp = "8b3812ef-8090-40aa-b736-e0885c8b05ad",
=======
                            PasswordHash = "AQAAAAIAAYagAAAAECIVsz508NI8+rWfjod4xKgRQ22xIlV7hgenZzGdpwMS2E5jemg8V8rrhDaMaSvvLQ==",
                            PhoneNumber = "+31 6 34567890",
                            PhoneNumberConfirmed = false,
                            PostalCode = "8329 SK",
                            SecurityStamp = "12e68812-41e7-48ab-8092-6b294d48d8e1",
>>>>>>> development
                            StartDate = new DateTime(2018, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UserName = "darlon.vandijk@hotmail.com"
                        },
                        new
                        {
                            Id = "b3c3d4e5-67f8-9a01-c2d3-e4f5g6h7i8j9",
                            AccessFailedCount = 0,
                            BID = "B004",
                            BirthDate = new DateTime(1980, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
<<<<<<< HEAD
                            ConcurrencyStamp = "cff4063b-c8f9-40ed-aadb-cb8ecb062f99",
=======
                            ConcurrencyStamp = "71e57c9d-8924-40ee-86a6-48e5d82b0312",
>>>>>>> development
                            Email = "pasha.bakker@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Pasha",
                            HouseNumber = 15,
                            IsSystemManager = false,
                            LastName = "Bakker",
                            LockoutEnabled = false,
                            ManagerOfBranchId = 3,
                            MiddleName = "",
                            NormalizedEmail = "PASHA.BAKKER@GMAIL.COM",
                            NormalizedUserName = "PASHA.BAKKER@GMAIL.COM",
<<<<<<< HEAD
                            PasswordHash = "AQAAAAIAAYagAAAAEFXm9iCROAWmKg3UWyy5/2QAH2ANG0oULTFIkZA8D0GoN28deRlzw03/TS9YRtJE3Q==",
                            PhoneNumber = "+31 6 45678901",
                            PhoneNumberConfirmed = false,
                            PostalCode = "3894 HT",
                            SecurityStamp = "6c75a1e7-23a1-4b84-8823-c736598aead8",
=======
                            PasswordHash = "AQAAAAIAAYagAAAAEJSLd5ckqRatuvPY4Xr4jWzdo0/HA9d44POcyZM/7d90I/Vp8deqekaLli0wn4jZ+w==",
                            PhoneNumber = "+31 6 45678901",
                            PhoneNumberConfirmed = false,
                            PostalCode = "3894 HT",
                            SecurityStamp = "cc541e05-5fb2-4192-93ee-41f00b9f8064",
>>>>>>> development
                            StartDate = new DateTime(2010, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UserName = "pasha.bakker@gmail.com"
                        },
                        new
                        {
                            Id = "c4d4e5f6-78g9-0a12-d3e4-f5g6h7i8j9k0",
                            AccessFailedCount = 0,
                            BID = "B005",
                            BirthDate = new DateTime(1988, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
<<<<<<< HEAD
                            ConcurrencyStamp = "95d97eee-9d07-479a-956f-024d49786c8f",
=======
                            ConcurrencyStamp = "4856a407-00d1-4e8d-a5a4-b5e82fbed3f5",
>>>>>>> development
                            Email = "sarah.vanderven@hotmail.com",
                            EmailConfirmed = false,
                            FirstName = "Sarah",
                            HouseNumber = 8,
                            IsSystemManager = false,
                            LastName = "van der Ven",
                            LockoutEnabled = false,
                            MiddleName = "",
                            NormalizedEmail = "SARAH.VANDERVEN@HOTMAIL.COM",
                            NormalizedUserName = "SARAH.VANDERVEN@HOTMAIL.COM",
<<<<<<< HEAD
                            PasswordHash = "AQAAAAIAAYagAAAAEAVOhZXXY+TN5iWKYogsZNM7O03Ln8tvC+ylh8hRz2cBC/P1zTcg/OKydYZMcKXUEA==",
                            PhoneNumber = "+31 6 56789012",
                            PhoneNumberConfirmed = false,
                            PostalCode = "2933 KJ",
                            SecurityStamp = "2d6d951a-64c5-4405-8d89-c347c9095e8f",
=======
                            PasswordHash = "AQAAAAIAAYagAAAAECPjSYym/6xTZWbUp3Sym7piOGk5+Zmz/5pLoE5XVW2tpUa21+iAsi1OpsXy2rZJDw==",
                            PhoneNumber = "+31 6 56789012",
                            PhoneNumberConfirmed = false,
                            PostalCode = "2933 KJ",
                            SecurityStamp = "6afadb66-ffe0-4813-b015-db37b9edda8d",
>>>>>>> development
                            StartDate = new DateTime(2017, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UserName = "sarah.vanderven@hotmail.com"
                        },
                        new
                        {
                            Id = "d5e5f6g7-89h0-1a23-e4f5-g6h7i8j9k0l1",
                            AccessFailedCount = 0,
                            BID = "B006",
                            BirthDate = new DateTime(1995, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
<<<<<<< HEAD
                            ConcurrencyStamp = "17c0fe96-96b7-4d38-a9ed-45942e13bdb7",
=======
                            ConcurrencyStamp = "c24a9c75-41da-426c-a8b3-4cbd6eff6d7f",
>>>>>>> development
                            Email = "david.denboer@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "David",
                            HouseNumber = 30,
                            IsSystemManager = false,
                            LastName = "den Boer",
                            LockoutEnabled = false,
                            ManagerOfBranchId = 2,
                            MiddleName = "",
                            NormalizedEmail = "DAVID.DENBOER@GMAIL.COM",
                            NormalizedUserName = "DAVID.DENBOER@GMAIL.COM",
<<<<<<< HEAD
                            PasswordHash = "AQAAAAIAAYagAAAAEJWrMqV8UCgRbqlsQuvd96ERTBsgrqHkzPK/juLp6hFAE9vGABHxE/3E9PIImQg+3g==",
                            PhoneNumber = "+31 6 67890123",
                            PhoneNumberConfirmed = false,
                            PostalCode = "4293 BF",
                            SecurityStamp = "ee7aa3c0-7944-4e26-a781-0a8c9feaef0e",
=======
                            PasswordHash = "AQAAAAIAAYagAAAAENu4if44C42t+hxoZ+EQeZROcFB2eDnDiaz3zLyX5fEEOhL+CbGPrvfxIMGcBHOjVg==",
                            PhoneNumber = "+31 6 67890123",
                            PhoneNumberConfirmed = false,
                            PostalCode = "4293 BF",
                            SecurityStamp = "d7f3bf0a-9247-43e4-b97b-cb7ab8d4e4b7",
>>>>>>> development
                            StartDate = new DateTime(2020, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UserName = "david.denboer@gmail.com"
                        },
                        new
                        {
                            Id = "a1b1c1d1-1111-2222-3333-4444abcdabcd",
                            AccessFailedCount = 0,
                            BID = "B012",
                            BirthDate = new DateTime(1993, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
<<<<<<< HEAD
                            ConcurrencyStamp = "44e49d4b-91b0-4b7c-886d-58e4fb08ab34",
=======
                            ConcurrencyStamp = "bba89b0e-08ee-4959-810a-e6a6c64209cc",
>>>>>>> development
                            Email = "anthony.ross@example.com",
                            EmailConfirmed = true,
                            FirstName = "Anthony",
                            HouseNumber = 7,
                            IsSystemManager = false,
                            LastName = "Ross",
                            LockoutEnabled = false,
                            ManagerOfBranchId = 1,
                            MiddleName = "",
                            NormalizedEmail = "ANTHONY.ROSS@EXAMPLE.COM",
                            NormalizedUserName = "ANTHONY.ROSS@EXAMPLE.COM",
<<<<<<< HEAD
                            PasswordHash = "AQAAAAIAAYagAAAAEF1mbGs2exxQ/WI4i45qS+IFPvQKztiAUE9H4cwkQTnB1hmqCxTGqPHVqGOwZKYhlQ==",
                            PhoneNumber = "+31 6 12345678",
                            PhoneNumberConfirmed = false,
                            PostalCode = "2234 AB",
                            SecurityStamp = "2bebb206-9ca6-436c-9d82-1a2c57df2603",
                            StartDate = new DateTime(2024, 11, 26, 13, 37, 7, 747, DateTimeKind.Local).AddTicks(7323),
=======
                            PasswordHash = "AQAAAAIAAYagAAAAEFoOHJGlXeNdAtp2bC+MoJUEVRAWCHh8+rr522iCH6efQ0vsAZa89b4i7+/UEmOv0A==",
                            PhoneNumber = "+31 6 12345678",
                            PhoneNumberConfirmed = false,
                            PostalCode = "2234 AB",
                            SecurityStamp = "d55d12fa-1b79-413b-9c13-c47450fb57f4",
                            StartDate = new DateTime(2024, 11, 25, 20, 7, 28, 94, DateTimeKind.Local).AddTicks(9484),
>>>>>>> development
                            TwoFactorEnabled = false,
                            UserName = "anthony.ross@example.com"
                        },
                        new
                        {
                            Id = "b2c2d2e2-2222-3333-4444-5555abcdefab",
                            AccessFailedCount = 0,
                            BID = "B013",
                            BirthDate = new DateTime(1987, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
<<<<<<< HEAD
                            ConcurrencyStamp = "e885f5c0-e439-4d4f-b5ed-56b3b61a4313",
=======
                            ConcurrencyStamp = "ab9a9688-69ab-4c23-87ac-defd60b28172",
>>>>>>> development
                            Email = "douwe.jansen@example.com",
                            EmailConfirmed = true,
                            FirstName = "Douwe",
                            HouseNumber = 12,
                            IsSystemManager = false,
                            LastName = "Jansen",
                            LockoutEnabled = false,
                            ManagerOfBranchId = 2,
                            MiddleName = "",
                            NormalizedEmail = "DOUWE.JANSEN@EXAMPLE.COM",
                            NormalizedUserName = "DOUWE.JANSEN@EXAMPLE.COM",
<<<<<<< HEAD
                            PasswordHash = "AQAAAAIAAYagAAAAEIuRcnktD/WiPMBwKaNplqGjPqaNTlFhf1ipoLTXHuBmnz0CURilnPH7x0XU0vPYdQ==",
                            PhoneNumber = "+31 6 87654321",
                            PhoneNumberConfirmed = false,
                            PostalCode = "3345 CD",
                            SecurityStamp = "6efa5039-980c-4c79-a7cd-322c351beadc",
                            StartDate = new DateTime(2024, 11, 26, 13, 37, 7, 798, DateTimeKind.Local).AddTicks(7534),
=======
                            PasswordHash = "AQAAAAIAAYagAAAAEDZrncxl+k2+WCsRUux+j74i5Oc3YTr+M9qn2h3/nLpY1vWP7zcKRf6TdKQjDoC7cw==",
                            PhoneNumber = "+31 6 87654321",
                            PhoneNumberConfirmed = false,
                            PostalCode = "3345 CD",
                            SecurityStamp = "ab0fb01e-fd59-40b2-bad9-ec42c1fc8816",
                            StartDate = new DateTime(2024, 11, 25, 20, 7, 28, 177, DateTimeKind.Local).AddTicks(1990),
>>>>>>> development
                            TwoFactorEnabled = false,
                            UserName = "douwe.jansen@example.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RequestStatus", b =>
                {
                    b.Property<string>("RequestStatusName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RequestStatusName");

                    b.ToTable("RequestStatus");

                    b.HasData(
                        new
                        {
                            RequestStatusName = "In Afwachting"
                        },
                        new
                        {
                            RequestStatusName = "Afgewezen"
                        },
                        new
                        {
                            RequestStatusName = "Geaccepteerd"
                        });
                });

            modelBuilder.Entity("bumbo.Models.BranchHasEmployee", b =>
                {
                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FunctionName")
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BranchId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("FunctionName");

                    b.ToTable("BranchHasEmployees");

                    b.HasData(
                        new
                        {
                            BranchId = 2,
                            EmployeeId = "d5e5f6g7-89h0-1a23-e4f5-g6h7i8j9k0l1",
                            FunctionName = "Manager",
                            StartDate = new DateTime(2020, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BranchId = 3,
                            EmployeeId = "b3c3d4e5-67f8-9a01-c2d3-e4f5g6h7i8j9",
                            FunctionName = "Manager",
                            StartDate = new DateTime(2010, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BranchId = 4,
                            EmployeeId = "a2b2d3e4-56f7-8a90-b1c2-d3e4f5g6h7i8",
                            FunctionName = "Stocker",
                            StartDate = new DateTime(2018, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BranchId = 3,
                            EmployeeId = "c4d4e5f6-78g9-0a12-d3e4-f5g6h7i8j9k0",
                            FunctionName = "Cashier",
                            StartDate = new DateTime(2017, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BranchId = 1,
                            EmployeeId = "a1b1c1d1-1111-2222-3333-4444abcdabcd",
                            FunctionName = "Cashier",
<<<<<<< HEAD
                            StartDate = new DateTime(2024, 11, 26, 13, 37, 7, 747, DateTimeKind.Local).AddTicks(7323)
=======
                            StartDate = new DateTime(2024, 11, 25, 20, 7, 28, 94, DateTimeKind.Local).AddTicks(9484)
>>>>>>> development
                        },
                        new
                        {
                            BranchId = 2,
                            EmployeeId = "b2c2d2e2-2222-3333-4444-5555abcdefab",
                            FunctionName = "Stocker",
<<<<<<< HEAD
                            StartDate = new DateTime(2024, 11, 26, 13, 37, 7, 798, DateTimeKind.Local).AddTicks(7534)
=======
                            StartDate = new DateTime(2024, 11, 25, 20, 7, 28, 177, DateTimeKind.Local).AddTicks(1990)
>>>>>>> development
                        });
                });

            modelBuilder.Entity("bumbo.Models.BranchRequestsEmployee", b =>
                {
                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RequestToBranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateNeeded")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("RequestStatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("BranchId", "EmployeeId", "RequestToBranchId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RequestStatusName");

                    b.HasIndex("RequestToBranchId");

                    b.ToTable("BranchRequestsEmployee");

                    b.HasData(
                        new
                        {
                            BranchId = 1,
                            EmployeeId = "b2c2d2e2-2222-3333-4444-5555abcdefab",
                            RequestToBranchId = 2,
                            DateNeeded = new DateTime(2024, 12, 2, 20, 7, 28, 261, DateTimeKind.Local).AddTicks(3010),
                            EndTime = new TimeOnly(17, 0, 0),
                            Message = "Overplaatsing nodig vanwege projectdeadline.",
                            RequestStatusName = "In Afwachting",
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            BranchId = 2,
                            EmployeeId = "a1b1c1d1-1111-2222-3333-4444abcdabcd",
                            RequestToBranchId = 1,
                            DateNeeded = new DateTime(2024, 12, 9, 20, 7, 28, 261, DateTimeKind.Local).AddTicks(3080),
                            EndTime = new TimeOnly(16, 0, 0),
                            Message = "Er zijn te weinig medewerkers op deze datum beschikbaar.",
                            RequestStatusName = "In Afwachting",
                            StartTime = new TimeOnly(12, 0, 0)
                        },
                        new
                        {
                            BranchId = 3,
                            EmployeeId = "a2b2d3e4-56f7-8a90-b1c2-d3e4f5g6h7i8",
                            RequestToBranchId = 4,
                            DateNeeded = new DateTime(2024, 12, 5, 20, 7, 28, 261, DateTimeKind.Local).AddTicks(3084),
                            EndTime = new TimeOnly(17, 30, 0),
                            Message = "Hulp nodig vanwege ziekte van een collega.",
                            RequestStatusName = "Afgewezen",
                            StartTime = new TimeOnly(8, 30, 0)
                        },
                        new
                        {
                            BranchId = 1,
                            EmployeeId = "c4d4e5f6-78g9-0a12-d3e4-f5g6h7i8j9k0",
                            RequestToBranchId = 3,
                            DateNeeded = new DateTime(2024, 12, 15, 20, 7, 28, 261, DateTimeKind.Local).AddTicks(3088),
                            EndTime = new TimeOnly(16, 0, 0),
                            Message = "Overplaatsing voor trainingssessies.",
                            RequestStatusName = "Geaccepteerd",
                            StartTime = new TimeOnly(9, 0, 0)
                        });
                });

            modelBuilder.Entity("bumbo.Models.Country", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Name");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Name = "Netherlands"
                        },
                        new
                        {
                            Name = "Belgium"
                        },
                        new
                        {
                            Name = "Germany"
                        });
                });

            modelBuilder.Entity("bumbo.Models.Days", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Name");

                    b.ToTable("Days");

                    b.HasData(
                        new
                        {
                            Name = "Maandag"
                        },
                        new
                        {
                            Name = "Dinsdag"
                        },
                        new
                        {
                            Name = "Woensdag"
                        },
                        new
                        {
                            Name = "Donderdag"
                        },
                        new
                        {
                            Name = "Vrijdag"
                        },
                        new
                        {
                            Name = "Zaterdag"
                        },
                        new
                        {
                            Name = "Zondag"
                        },
                        new
                        {
                            Name = "Monday"
                        },
                        new
                        {
                            Name = "Tuesday"
                        },
                        new
                        {
                            Name = "Wednesday"
                        },
                        new
                        {
                            Name = "Thursday"
                        },
                        new
                        {
                            Name = "Friday"
                        },
                        new
                        {
                            Name = "Saturday"
                        },
                        new
                        {
                            Name = "Sunday"
                        });
                });

            modelBuilder.Entity("bumbo.Models.Norm", b =>
                {
                    b.Property<int>("normId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("normId"));

                    b.Property<string>("activity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("branchId")
                        .HasColumnType("int");

                    b.Property<int>("normInSeconds")
                        .HasColumnType("int");

                    b.Property<int>("week")
                        .HasColumnType("int");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("normId");

                    b.HasIndex("branchId", "year", "week", "activity")
                        .IsUnique();

                    b.ToTable("Norms");

                    b.HasData(
                        new
                        {
                            normId = 1,
                            activity = "Coli uitladen",
                            branchId = 1,
                            normInSeconds = 90,
                            week = 41,
                            year = 2024
                        },
                        new
                        {
                            normId = 2,
                            activity = "Vakkenvullen",
                            branchId = 1,
                            normInSeconds = 33,
                            week = 41,
                            year = 2024
                        },
                        new
                        {
                            normId = 3,
                            activity = "Kassa",
                            branchId = 1,
                            normInSeconds = 3,
                            week = 41,
                            year = 2024
                        },
                        new
                        {
                            normId = 4,
                            activity = "Vers",
                            branchId = 1,
                            normInSeconds = 7,
                            week = 41,
                            year = 2024
                        },
                        new
                        {
                            normId = 5,
                            activity = "Spiegelen",
                            branchId = 1,
                            normInSeconds = 2,
                            week = 41,
                            year = 2024
                        });
                });

            modelBuilder.Entity("bumbo.Models.Prognosis", b =>
                {
                    b.Property<string>("PrognosisId")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("WeekNr")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("PrognosisId");

                    b.HasIndex("BranchId");

                    b.ToTable("Prognoses");

                    b.HasData(
                        new
                        {
                            PrognosisId = "1",
                            BranchId = 1,
                            WeekNr = 40,
                            Year = 2024
                        },
                        new
                        {
                            PrognosisId = "2",
                            BranchId = 1,
                            WeekNr = 20,
                            Year = 2024
                        },
                        new
                        {
                            PrognosisId = "prognosis_week_47_2024",
                            BranchId = 1,
                            WeekNr = 47,
                            Year = 2024
                        });
                });

            modelBuilder.Entity("bumbo.Models.PrognosisHasDays", b =>
                {
                    b.Property<string>("DayName")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PrognosisId")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("CustomerAmount")
                        .HasColumnType("int");

                    b.Property<int>("PackagesAmount")
                        .HasColumnType("int");

                    b.HasKey("DayName", "PrognosisId");

                    b.HasIndex("PrognosisId");

                    b.ToTable("PrognosisHasDays");

                    b.HasData(
                        new
                        {
                            DayName = "Maandag",
                            PrognosisId = "1",
                            CustomerAmount = 100,
                            PackagesAmount = 50
                        },
                        new
                        {
                            DayName = "Dinsdag",
                            PrognosisId = "1",
                            CustomerAmount = 120,
                            PackagesAmount = 60
                        },
                        new
                        {
                            DayName = "Woensdag",
                            PrognosisId = "1",
                            CustomerAmount = 130,
                            PackagesAmount = 55
                        },
                        new
                        {
                            DayName = "Donderdag",
                            PrognosisId = "1",
                            CustomerAmount = 110,
                            PackagesAmount = 45
                        },
                        new
                        {
                            DayName = "Vrijdag",
                            PrognosisId = "1",
                            CustomerAmount = 150,
                            PackagesAmount = 70
                        },
                        new
                        {
                            DayName = "Zaterdag",
                            PrognosisId = "1",
                            CustomerAmount = 160,
                            PackagesAmount = 80
                        },
                        new
                        {
                            DayName = "Zondag",
                            PrognosisId = "1",
                            CustomerAmount = 140,
                            PackagesAmount = 65
                        },
                        new
                        {
                            DayName = "Maandag",
                            PrognosisId = "2",
                            CustomerAmount = 90,
                            PackagesAmount = 40
                        },
                        new
                        {
                            DayName = "Dinsdag",
                            PrognosisId = "2",
                            CustomerAmount = 115,
                            PackagesAmount = 55
                        },
                        new
                        {
                            DayName = "Woensdag",
                            PrognosisId = "2",
                            CustomerAmount = 125,
                            PackagesAmount = 50
                        },
                        new
                        {
                            DayName = "Donderdag",
                            PrognosisId = "2",
                            CustomerAmount = 105,
                            PackagesAmount = 42
                        },
                        new
                        {
                            DayName = "Vrijdag",
                            PrognosisId = "2",
                            CustomerAmount = 140,
                            PackagesAmount = 68
                        },
                        new
                        {
                            DayName = "Zaterdag",
                            PrognosisId = "2",
                            CustomerAmount = 150,
                            PackagesAmount = 75
                        },
                        new
                        {
                            DayName = "Zondag",
                            PrognosisId = "2",
                            CustomerAmount = 130,
                            PackagesAmount = 60
                        },
                        new
                        {
                            DayName = "Monday",
                            PrognosisId = "prognosis_week_47_2024",
                            CustomerAmount = 200,
                            PackagesAmount = 300
                        },
                        new
                        {
                            DayName = "Tuesday",
                            PrognosisId = "prognosis_week_47_2024",
                            CustomerAmount = 150,
                            PackagesAmount = 250
                        },
                        new
                        {
                            DayName = "Wednesday",
                            PrognosisId = "prognosis_week_47_2024",
                            CustomerAmount = 220,
                            PackagesAmount = 280
                        },
                        new
                        {
                            DayName = "Thursday",
                            PrognosisId = "prognosis_week_47_2024",
                            CustomerAmount = 190,
                            PackagesAmount = 270
                        },
                        new
                        {
                            DayName = "Friday",
                            PrognosisId = "prognosis_week_47_2024",
                            CustomerAmount = 210,
                            PackagesAmount = 290
                        },
                        new
                        {
                            DayName = "Saturday",
                            PrognosisId = "prognosis_week_47_2024",
                            CustomerAmount = 250,
                            PackagesAmount = 320
                        },
                        new
                        {
                            DayName = "Sunday",
                            PrognosisId = "prognosis_week_47_2024",
                            CustomerAmount = 180,
                            PackagesAmount = 260
                        });
                });

            modelBuilder.Entity("bumbo.Models.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchBranchId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("BranchBranchId");

                    b.ToTable("Templates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchBranchId = 1,
                            Name = "Basic Package"
                        },
                        new
                        {
                            Id = 2,
                            BranchBranchId = 1,
                            Name = "Standard Package"
                        },
                        new
                        {
                            Id = 3,
                            BranchBranchId = 2,
                            Name = "Premium Package"
                        },
                        new
                        {
                            Id = 4,
                            BranchBranchId = 2,
                            Name = "Family Package"
                        },
                        new
                        {
                            Id = 5,
                            BranchBranchId = 1,
                            Name = "Weekly Special"
                        });
                });

            modelBuilder.Entity("bumbo.Models.TemplateHasDays", b =>
                {
                    b.Property<int>("TemplatesId")
                        .HasColumnType("int");

                    b.Property<string>("DaysName")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ContainerAmount")
                        .HasColumnType("int");

                    b.Property<int>("CustomerAmount")
                        .HasColumnType("int");

                    b.HasKey("TemplatesId", "DaysName");

                    b.HasIndex("DaysName");

                    b.ToTable("TemplateHasDays");

                    b.HasData(
                        new
                        {
                            TemplatesId = 1,
                            DaysName = "Monday",
                            ContainerAmount = 41,
                            CustomerAmount = 989
                        },
                        new
                        {
                            TemplatesId = 1,
                            DaysName = "Tuesday",
                            ContainerAmount = 52,
                            CustomerAmount = 825
                        },
                        new
                        {
                            TemplatesId = 1,
                            DaysName = "Wednesday",
                            ContainerAmount = 38,
                            CustomerAmount = 902
                        },
                        new
                        {
                            TemplatesId = 1,
                            DaysName = "Thursday",
                            ContainerAmount = 52,
                            CustomerAmount = 990
                        },
                        new
                        {
                            TemplatesId = 1,
                            DaysName = "Friday",
                            ContainerAmount = 39,
                            CustomerAmount = 1040
                        },
                        new
                        {
                            TemplatesId = 1,
                            DaysName = "Saturday",
                            ContainerAmount = 43,
                            CustomerAmount = 953
                        },
                        new
                        {
                            TemplatesId = 1,
                            DaysName = "Sunday",
                            ContainerAmount = 32,
                            CustomerAmount = 872
                        },
                        new
                        {
                            TemplatesId = 2,
                            DaysName = "Monday",
                            ContainerAmount = 42,
                            CustomerAmount = 916
                        },
                        new
                        {
                            TemplatesId = 2,
                            DaysName = "Tuesday",
                            ContainerAmount = 38,
                            CustomerAmount = 912
                        },
                        new
                        {
                            TemplatesId = 2,
                            DaysName = "Wednesday",
                            ContainerAmount = 32,
                            CustomerAmount = 902
                        },
                        new
                        {
                            TemplatesId = 2,
                            DaysName = "Thursday",
                            ContainerAmount = 45,
                            CustomerAmount = 940
                        },
                        new
                        {
                            TemplatesId = 2,
                            DaysName = "Friday",
                            ContainerAmount = 47,
                            CustomerAmount = 816
                        },
                        new
                        {
                            TemplatesId = 2,
                            DaysName = "Saturday",
                            ContainerAmount = 38,
                            CustomerAmount = 842
                        },
                        new
                        {
                            TemplatesId = 2,
                            DaysName = "Sunday",
                            ContainerAmount = 45,
                            CustomerAmount = 885
                        },
                        new
                        {
                            TemplatesId = 3,
                            DaysName = "Monday",
                            ContainerAmount = 53,
                            CustomerAmount = 872
                        },
                        new
                        {
                            TemplatesId = 3,
                            DaysName = "Tuesday",
                            ContainerAmount = 41,
                            CustomerAmount = 989
                        },
                        new
                        {
                            TemplatesId = 3,
                            DaysName = "Wednesday",
                            ContainerAmount = 42,
                            CustomerAmount = 916
                        },
                        new
                        {
                            TemplatesId = 3,
                            DaysName = "Thursday",
                            ContainerAmount = 36,
                            CustomerAmount = 875
                        },
                        new
                        {
                            TemplatesId = 3,
                            DaysName = "Friday",
                            ContainerAmount = 29,
                            CustomerAmount = 877
                        },
                        new
                        {
                            TemplatesId = 3,
                            DaysName = "Saturday",
                            ContainerAmount = 53,
                            CustomerAmount = 945
                        },
                        new
                        {
                            TemplatesId = 3,
                            DaysName = "Sunday",
                            ContainerAmount = 52,
                            CustomerAmount = 880
                        },
                        new
                        {
                            TemplatesId = 4,
                            DaysName = "Monday",
                            ContainerAmount = 49,
                            CustomerAmount = 900
                        },
                        new
                        {
                            TemplatesId = 4,
                            DaysName = "Tuesday",
                            ContainerAmount = 38,
                            CustomerAmount = 903
                        },
                        new
                        {
                            TemplatesId = 4,
                            DaysName = "Wednesday",
                            ContainerAmount = 45,
                            CustomerAmount = 930
                        },
                        new
                        {
                            TemplatesId = 4,
                            DaysName = "Thursday",
                            ContainerAmount = 42,
                            CustomerAmount = 985
                        },
                        new
                        {
                            TemplatesId = 4,
                            DaysName = "Friday",
                            ContainerAmount = 36,
                            CustomerAmount = 865
                        },
                        new
                        {
                            TemplatesId = 4,
                            DaysName = "Saturday",
                            ContainerAmount = 43,
                            CustomerAmount = 950
                        },
                        new
                        {
                            TemplatesId = 4,
                            DaysName = "Sunday",
                            ContainerAmount = 38,
                            CustomerAmount = 950
                        },
                        new
                        {
                            TemplatesId = 5,
                            DaysName = "Monday",
                            ContainerAmount = 52,
                            CustomerAmount = 832
                        },
                        new
                        {
                            TemplatesId = 5,
                            DaysName = "Tuesday",
                            ContainerAmount = 49,
                            CustomerAmount = 935
                        },
                        new
                        {
                            TemplatesId = 5,
                            DaysName = "Wednesday",
                            ContainerAmount = 29,
                            CustomerAmount = 877
                        },
                        new
                        {
                            TemplatesId = 5,
                            DaysName = "Thursday",
                            ContainerAmount = 41,
                            CustomerAmount = 989
                        },
                        new
                        {
                            TemplatesId = 5,
                            DaysName = "Friday",
                            ContainerAmount = 32,
                            CustomerAmount = 872
                        },
                        new
                        {
                            TemplatesId = 5,
                            DaysName = "Saturday",
                            ContainerAmount = 36,
                            CustomerAmount = 771
                        },
                        new
                        {
                            TemplatesId = 5,
                            DaysName = "Sunday",
                            ContainerAmount = 52,
                            CustomerAmount = 885
                        });
                });

            modelBuilder.Entity("Branch", b =>
                {
                    b.HasOne("bumbo.Models.Country", "Country")
                        .WithMany("Branches")
                        .HasForeignKey("CountryName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bumbo.Models.Prognosis", null)
                        .WithMany("Branches")
                        .HasForeignKey("PrognosisId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("DataLayer.Models.Availability", b =>
                {
                    b.HasOne("Employee", "Employee")
                        .WithMany("Availabilitys")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DataLayer.Models.EmployeeHasDepartment", b =>
                {
                    b.HasOne("DataLayer.Models.Department", "Department")
                        .WithMany("EmployeeHasDepartment")
                        .HasForeignKey("DepartmentName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Employee", "Employee")
                        .WithMany("EmployeeHasDepartment")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DataLayer.Models.LabourRules", b =>
                {
                    b.HasOne("bumbo.Models.Country", "Country")
                        .WithMany("LabourRules")
                        .HasForeignKey("CountryName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("DataLayer.Models.PrognosisHasDaysHasDepartment", b =>
                {
                    b.HasOne("DataLayer.Models.Department", "Department")
                        .WithMany("PrognosisHasDaysHasDepartment")
                        .HasForeignKey("DepartmentName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bumbo.Models.PrognosisHasDays", "PrognosisHasDays")
                        .WithMany("PrognosisHasDaysHasDepartment")
                        .HasForeignKey("DayName", "PrognosisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("PrognosisHasDays");
                });

            modelBuilder.Entity("DataLayer.Models.Schedule", b =>
                {
                    b.HasOne("Branch", "Branch")
                        .WithMany("Schedules")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Models.Department", "Department")
                        .WithMany("Schedules")
                        .HasForeignKey("DepartmentName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Employee", "Employee")
                        .WithMany("Schedules")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bumbo.Models.Template", null)
                        .WithMany("Schedules")
                        .HasForeignKey("TemplateId");

                    b.Navigation("Branch");

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DataLayer.Models.SchoolSchedule", b =>
                {
                    b.HasOne("Employee", "Employee")
                        .WithMany("SchoolSchedules")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DataLayer.Models.SwitchRequest", b =>
                {
                    b.HasOne("Employee", "Employee")
                        .WithMany("SwitchRequests")
                        .HasForeignKey("SendToEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataLayer.Models.Schedule", "Schedule")
                        .WithMany("SwitchRequests")
                        .HasForeignKey("EmployeeId", "BranchId", "Date")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Employee", b =>
                {
                    b.HasOne("Branch", "ManagerOfBranch")
                        .WithMany("Employees")
                        .HasForeignKey("ManagerOfBranchId");

                    b.Navigation("ManagerOfBranch");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Employee", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Employee", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Employee", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Employee", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("bumbo.Models.BranchHasEmployee", b =>
                {
                    b.HasOne("Branch", "Branch")
                        .WithMany("BranchHasEmployees")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Employee", "Employee")
                        .WithMany("BranchEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Models.Function", "Function")
                        .WithMany()
                        .HasForeignKey("FunctionName");

                    b.Navigation("Branch");

                    b.Navigation("Employee");

                    b.Navigation("Function");
                });

            modelBuilder.Entity("bumbo.Models.BranchRequestsEmployee", b =>
                {
                    b.HasOne("Employee", "Employee")
                        .WithMany("BranchRequestsEmployee")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RequestStatus", "RequestStatus")
                        .WithMany("BranchRequestsEmployee")
                        .HasForeignKey("RequestStatusName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Branch", "Branch")
                        .WithMany("BranchRequestsEmployee")
                        .HasForeignKey("RequestToBranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Employee");

                    b.Navigation("RequestStatus");
                });

            modelBuilder.Entity("bumbo.Models.Norm", b =>
                {
                    b.HasOne("Branch", "Branch")
                        .WithMany("Norm")
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("bumbo.Models.Prognosis", b =>
                {
                    b.HasOne("Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("bumbo.Models.PrognosisHasDays", b =>
                {
                    b.HasOne("bumbo.Models.Days", "Days")
                        .WithMany("PrognosisHasDays")
                        .HasForeignKey("DayName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bumbo.Models.Prognosis", "Prognosis")
                        .WithMany("PrognosisHasDays")
                        .HasForeignKey("PrognosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Days");

                    b.Navigation("Prognosis");
                });

            modelBuilder.Entity("bumbo.Models.Template", b =>
                {
                    b.HasOne("Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("bumbo.Models.TemplateHasDays", b =>
                {
                    b.HasOne("bumbo.Models.Days", "Days")
                        .WithMany("TemplateHasDays")
                        .HasForeignKey("DaysName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bumbo.Models.Template", "Template")
                        .WithMany("TemplateHasDays")
                        .HasForeignKey("TemplatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Days");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Branch", b =>
                {
                    b.Navigation("BranchHasEmployees");

                    b.Navigation("BranchRequestsEmployee");

                    b.Navigation("Employees");

                    b.Navigation("Norm");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("DataLayer.Models.Department", b =>
                {
                    b.Navigation("EmployeeHasDepartment");

                    b.Navigation("PrognosisHasDaysHasDepartment");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("DataLayer.Models.Schedule", b =>
                {
                    b.Navigation("SwitchRequests");
                });

            modelBuilder.Entity("Employee", b =>
                {
                    b.Navigation("Availabilitys");

                    b.Navigation("BranchEmployees");

                    b.Navigation("BranchRequestsEmployee");

                    b.Navigation("EmployeeHasDepartment");

                    b.Navigation("Schedules");

                    b.Navigation("SchoolSchedules");

                    b.Navigation("SwitchRequests");
                });

            modelBuilder.Entity("RequestStatus", b =>
                {
                    b.Navigation("BranchRequestsEmployee");
                });

            modelBuilder.Entity("bumbo.Models.Country", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("LabourRules");
                });

            modelBuilder.Entity("bumbo.Models.Days", b =>
                {
                    b.Navigation("PrognosisHasDays");

                    b.Navigation("TemplateHasDays");
                });

            modelBuilder.Entity("bumbo.Models.Prognosis", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("PrognosisHasDays");
                });

            modelBuilder.Entity("bumbo.Models.PrognosisHasDays", b =>
                {
                    b.Navigation("PrognosisHasDaysHasDepartment");
                });

            modelBuilder.Entity("bumbo.Models.Template", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("TemplateHasDays");
                });
#pragma warning restore 612, 618
        }
    }
}
