name: Build and deploy ASP.Net Core app to Azure Web App - bumbo-webapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:                   # Add this section to enable id-token permissions globally
  id-token: write
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the code from the repo
      - uses: actions/checkout@v4

      # Set up .NET Core
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Build with dotnet
      - name: Build with dotnet
        run: dotnet build bumbo/bumbo.csproj --configuration Release

      # Publish the application
      - name: Publish .NET app
        run: dotnet publish bumbo/bumbo.csproj -c Release -o ${{ github.workspace }}/published_app

      # Upload the published files for the deploy job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/published_app

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
    steps:
      # Download the published files
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      # Login to Azure using OIDC
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: 80fb242c-5dca-496a-a149-841188dd4bb8   # Your app registration's client ID
          tenant-id: 87c50b58-2ef2-423d-a4db-1fa7c84efcfa    # Your tenant ID
          subscription-id: 7c86441b-4dca-49f3-b903-89a3a711343f

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bumbo-webapp'
          package: ${{ github.workspace }}/published_app
